name: Spellcheck Action

on:
  # Enabling manual test
  # REF: https://stackoverflow.com/questions/58933155/manual-workflow-triggers-in-github-actions
  workflow_dispatch:
  push:

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:

    # The checkout step
    - uses: actions/checkout@v3

    - uses: rojopolis/spellcheck-github-actions@0.23.2
      name: Spellcheck
      with:
        source_files: README.md CHANGELOG.md
        task_name: Markdown

    - uses: shrink/actions-docker-extract@v1
      id: extract
      with:
        image: rojopolis/spellcheck-github-actions@0.23.2
        path: /tmp/run-report.txt

    - uses: actions/upload-artifact@v3
      name: Archive workflow run output
      with:
        name: run-report
        path: ${{ steps.extract.outputs.destination }}
